### ISSUE TITLE
ionic serve issue

### ISSUE THREAD

**Issue by smokR-spr** [TheMathematicians/physio-ng2#1]
Getting this error while running ionic serve

**'ionic-app-scripts' is not recognized as an internal or external command,
operable program or batch file.**

```
> ionic-hello-world@0.0.0 ionic:serve E:\__\physio-ng2
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

'ionic-app-scripts' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "3
5729"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@0.0.0 ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "
8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@0.0.0 ionic:serve script 'ionic-app-scripts serve "--v2" "--address"
"0.0.0.0" "--port" "8100" "--livereload-port" "35729"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\__\physio-ng2\npm-debug.log
There was an error serving your Ionic application: There was an error with the spawned command: serve
```

**Comment by smokR-spr** [comment]
* Ran the following `npm install @ionic/app-scripts@latest --save-dev`
```
> npm install @ionic/app-scripts@latest --save-dev
npm WARN prefer global node-gyp@3.6.1 should be installed with -g
physio-ng2@0.0.0 E:\__\physio-ng2
`-- @ionic/app-scripts@1.3.6
  +-- node-sass@4.5.0
  | `-- node-gyp@3.6.1
  `-- webpack@2.2.1
    `-- async@2.4.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","
arch":"any"} (current: {"os":"win32","arch":"x64"})
```

* Then ran `./node_modules/.bin/ionic-app-scripts serve`
```
> ./node_modules/.bin/ionic-app-scripts serve
E:\__\physio-ng2\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding E:\__\physio-ng2\node_modules\node-sass\vendor\win32-x64-51\bind
ing.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (E:\__\physio-ng2\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (E:\__\physio-ng2\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\__\physio-ng2\node_modules\@ionic\app-scripts\dist\core\b
undle-components.js:6:16)
```

* This issue shows that 
**Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x**

  **Found bindings for the following environments:**
  **- Linux 64-bit with Node.js 6.x**

* Ran `npm rebuild node-sass`

* **Now `ionic serve` works!**
